
spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/wms?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 0
    password:

mybatis:
  mapper-locations: classpath:adminmapper/*.xml, classpath:mapper/*.xml
  type-aliases-package: com.wms.vo,com.wms.user.service.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





